using System;
using System.Collections.Generic;
using BansheeGz.BGDatabase;

//=============================================================
//||                   Generated by BansheeGz Code Generator ||
//=============================================================

#pragma warning disable 414

public partial class MyTable : BGEntity
{

	public class Factory : BGEntity.EntityFactory
	{
		public BGEntity NewEntity(BGMetaEntity meta) => new MyTable(meta);
		public BGEntity NewEntity(BGMetaEntity meta, BGId id) => new MyTable(meta, id);
	}
	private static BansheeGz.BGDatabase.BGMetaRow _metaDefault;
	public static BansheeGz.BGDatabase.BGMetaRow MetaDefault => _metaDefault ?? (_metaDefault = BGCodeGenUtils.GetMeta<BansheeGz.BGDatabase.BGMetaRow>(new BGId(5579931681946199927UL,17116495601821238438UL), () => _metaDefault = null));
	public static BansheeGz.BGDatabase.BGRepoEvents Events => BGRepo.I.Events;
	public static int CountEntities => MetaDefault.CountEntities;
	public System.String name
	{
		get => _name[Index];
		set => _name[Index] = value;
	}
	public System.Single speed
	{
		get => _speed[Index];
		set => _speed[Index] = value;
	}
	public System.Int32 Identity
	{
		get => _Identity[Index];
		set => _Identity[Index] = value;
	}
	private static BansheeGz.BGDatabase.BGFieldEntityName _ufle12jhs77_name;
	public static BansheeGz.BGDatabase.BGFieldEntityName _name => _ufle12jhs77_name ?? (_ufle12jhs77_name = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldEntityName>(MetaDefault, new BGId(5307582292816005461UL, 2379966240639056038UL), () => _ufle12jhs77_name = null));
	private static BansheeGz.BGDatabase.BGFieldFloat _ufle12jhs77_speed;
	public static BansheeGz.BGDatabase.BGFieldFloat _speed => _ufle12jhs77_speed ?? (_ufle12jhs77_speed = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldFloat>(MetaDefault, new BGId(5382768312300724909UL, 3990299174977381803UL), () => _ufle12jhs77_speed = null));
	private static BansheeGz.BGDatabase.BGFieldInt _ufle12jhs77_Identity;
	public static BansheeGz.BGDatabase.BGFieldInt _Identity => _ufle12jhs77_Identity ?? (_ufle12jhs77_Identity = BGCodeGenUtils.GetField<BansheeGz.BGDatabase.BGFieldInt>(MetaDefault, new BGId(5670844434519759250UL, 893360460844666241UL), () => _ufle12jhs77_Identity = null));
	private static readonly MyTable.Factory _factory0_PFS = new MyTable.Factory();
	private MyTable() : base(MetaDefault)
	{
	}
	private MyTable(BGId id) : base(MetaDefault, id)
	{
	}
	private MyTable(BGMetaEntity meta) : base(meta)
	{
	}
	private MyTable(BGMetaEntity meta, BGId id) : base(meta, id)
	{
	}
	public static MyTable FindEntity(Predicate<MyTable> filter)
	{
		return MetaDefault.FindEntity(entity => filter==null || filter((MyTable) entity)) as MyTable;
	}
	public static List<MyTable> FindEntities(Predicate<MyTable> filter, List<MyTable> result=null, Comparison<MyTable> sort=null) => BGCodeGenUtils.FindEntities(MetaDefault, filter, result, sort);
	public static void ForEachEntity(Action<MyTable> action, Predicate<MyTable> filter=null, Comparison<MyTable> sort=null)
	{
		MetaDefault.ForEachEntity(entity => action((MyTable) entity), filter == null ? null : (Predicate<BGEntity>) (entity => filter((MyTable) entity)), sort==null?(Comparison<BGEntity>) null:(e1,e2) => sort((MyTable)e1,(MyTable)e2));
	}
	public static MyTable GetEntity(BGId entityId) => (MyTable) MetaDefault.GetEntity(entityId);
	public static MyTable GetEntity(int index) => (MyTable) MetaDefault[index];
	public static MyTable GetEntity(string entityName) => (MyTable) MetaDefault.GetEntity(entityName);
	public static MyTable NewEntity() => (MyTable) MetaDefault.NewEntity();
	public static MyTable NewEntity(BGId entityId) => (MyTable) MetaDefault.NewEntity(entityId);
	public static MyTable NewEntity(Action<MyTable> callback)
	{
		return (MyTable) MetaDefault.NewEntity(new BGMetaEntity.NewEntityContext(entity => callback((MyTable)entity)));
	}
}
#pragma warning restore 414
